name: taramx
include:
  - path: ./taracert/compose.dev.yml
services:
  unbound:
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      start_period: 0s
      interval: 1s
      timeout: 1s
      retries: 1
