#!/bin/bash

trap "postfix stop" EXIT

until dig +short github.com > /dev/null; do
  echo "Waiting for DNS..."
  sleep 1
done

cat <<EOF > /etc/aliases
# Autogenerated
null: /dev/null
EOF
newaliases;

# Create SNI configuration
if [[ "${SKIP_LETS_ENCRYPT}" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
  echo -n "" > /opt/postfix/conf/sni.map
else
  echo -n "" > /opt/postfix/conf/sni.map;
  for cert_dir in /etc/letsencrypt/live/*/ ; do
    if [[ ! -f ${cert_dir}domains ]] || [[ ! -f ${cert_dir}fullchain.pem ]] || [[ ! -f ${cert_dir}privkey.pem ]]; then
      continue;
    fi
    IFS=" " read -r -a domains <<< "$(cat "${cert_dir}domains")"
    for domain in "${domains[@]}"; do
      echo -n "${domain} ${cert_dir}privkey.pem ${cert_dir}fullchain.pem" >> /opt/postfix/conf/sni.map;
      echo "" >> /opt/postfix/conf/sni.map;
    done
  done
fi
postmap -F hash:/opt/postfix/conf/sni.map;

# Generate relay domains map from environment variable
if [[ -n "${RELAY_DOMAINS}" ]]; then
  echo -n "" > /opt/postfix/conf/relay_domains
  IFS=',' read -r -a domains <<< "${RELAY_DOMAINS}"
  for domain in "${domains[@]}"; do
    domain=$(echo "${domain}" | xargs)
    echo "${domain} OK" >> /opt/postfix/conf/relay_domains
  done
  postmap hash:/opt/postfix/conf/relay_domains
fi

# Create SASL credentials for submission authentication
if [[ -n "${SUBMISSION_USER}" ]] && [[ -n "${SUBMISSION_PASS}" ]]; then
  echo "${SUBMISSION_PASS}" | saslpasswd2 -p -c -u "${MX_HOSTNAME}" "${SUBMISSION_USER}"
  chown postfix /etc/sasldb2
fi

# Reset main.cf
sed -i '/Overrides/q' /opt/postfix/conf/main.cf
echo >> /opt/postfix/conf/main.cf

# Append user overrides
echo -e "\n# User Overrides" >> /opt/postfix/conf/main.cf
touch /opt/postfix/conf/extra.cf
sed -i '/\$myhostname/! { /myhostname/d }' /opt/postfix/conf/extra.cf
echo -e "myhostname = ${MX_HOSTNAME}\n$(cat /opt/postfix/conf/extra.cf)" > /opt/postfix/conf/extra.cf

# Set relay transport to downstream mail server
if [[ -n "${RELAY_HOST}" ]]; then
  sed -i '/relay_transport/d' /opt/postfix/conf/extra.cf
  echo "relay_transport = smtp:[${RELAY_HOST}]:25" >> /opt/postfix/conf/extra.cf
fi

cat /opt/postfix/conf/extra.cf >> /opt/postfix/conf/main.cf

if [ ! -f /opt/postfix/conf/custom_postscreen_whitelist.cidr ]; then
  echo "Creating dummy custom_postscreen_whitelist.cidr"
  cat <<EOF > /opt/postfix/conf/custom_postscreen_whitelist.cidr
# Autogenerated
# Rules are evaluated in the order as specified.
# Blacklist 192.168.* except 192.168.0.1.
# 192.168.0.1          permit
# 192.168.0.0/16       reject
EOF
fi

# Fix Postfix permissions
chgrp -R postdrop /var/spool/postfix/public
chgrp -R postdrop /var/spool/postfix/maildrop
postfix set-permissions

# Checking if there is a leftover of a crashed postfix container before starting a new one
if [ -e /var/spool/postfix/pid/master.pid ]; then
  rm -rf /var/spool/postfix/pid/master.pid
fi

# Check Postfix configuration
postconf -c /opt/postfix/conf > /dev/null

if [[ $? != 0 ]]; then
  echo "Postfix configuration error, refusing to start."
  exit 1
else
  postfix -c /opt/postfix/conf start
  sleep 126144000
fi
